### ISSUE TITLE
New-TervisVM VMNameWithoutEnvironmentPrefix parameter does not accept non alpha-numeric characters. 

### ISSUE THREAD

**Issue by mastermohl** [Tervis-Tumbler/TervisVirtualization#5]
While creating a new VM, supplying a VM name which includes dashes for the VMNameWithoutEnvironmentPrefix parameter errors with the following:

`New-TervisVM : Cannot validate argument on parameter 'VMNameWithoutEnvironmentPrefix'. The VMNameWithoutEnvironmentPrefix should only contain alphanumeric
characters.
At line:1 char:46
- New-TervisVM -VMNameWithoutEnvironmentPrefix VNX-MR-2 -VMSizeName Med ...
-                                              ~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [New-TervisVM], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationError,New-TervisVM`

**Comment by ChrisMagnuson** [comment]
This is by design. Our current naming convention should be Prefix-NameOfVM without any other symbols or suffixes.
