### ISSUE TITLE
Error occurs while setting vmfirmware but build completes successfully

### ISSUE THREAD

**Issue by mastermohl** [Tervis-Tumbler/TervisVirtualization#6]
Build completes and is usable. Boot order is not changed from network boot.

![image](https://cloud.githubusercontent.com/assets/12830027/16804113/257f116e-48d8-11e6-9089-17327e2489ed.png)

**Comment by ChrisMagnuson** [comment]
This is the lines that need to be worked on, need to test this to figure out what the issue is:

``` PowerShell
$VM |
Add-VMHardDiskDrive -Path $PathOfVMVHDx -Passthru |
Set-VMFirmware -BootOrder $($vm | Get-VMHardDiskDrive)
```

**Comment by ChrisMagnuson** [comment]
Confirmed this is now working without errors.
